### ISSUE TITLE
CJS and ESM issue

### ISSUE THREAD

**Issue by winston0410** [keenethics/svelte-notifications#53]
Using this library with SvelteKit, I received the following error message:

```
svelte-notifications doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

**Comment by rationalquality** [comment]
Please, clone code from this repository: https://github.com/usernamus/svelte-notifications-cjs-esm-issue

I ran and built this project, no issues here. Try it on your computer. Let me know how it works

**Comment by winston0410** [comment]
![1643117949](https://user-images.githubusercontent.com/59228178/150987394-aab57927-68c4-4515-a9fd-2d471a24b0a5.jpg)

I suspect it might because of different Sveltekit version. Which sveltekit are you using in your machine(as npm might gives you a cached one)

**Comment by rationalquality** [comment]
The same SvelteKit version for me, but I'm using macOS. I'll try to find a computer with Windows and reproduce the issue. 

What version of node are you using?

**Comment by winston0410** [comment]
I am using `16.13.0` when I run that repo, and I was using Linux (NixOS). What version of node were you using?

**Comment by chbert** [comment]
Just in case it helps, same error here:
- Mac OS X 12.1
- "svelte-notifications": "^0.9.93",
- "svelte": "^3.46.3",
- "@sveltejs/kit": "next",

**Comment by rationalquality** [comment]
Guys I'm working on this. So far I haven't spent much time but I hope I can fix this

**Comment by jonjes** [comment]
I'm still trying to find a workaround for this, since it's stopping the development of a project that uses svelte-notifications.
In case it helps, here is the error message that I see. Maybe there's a better way to import the popper library?

```pre
svelte-notifications doesn't appear to be written in CJS...

Cannot use import statement outside a module
[project_dir]/node_modules/@popperjs/core/dist/esm/popper.js:1
import { popperGenerator, detectOverflow } from "./createPopper.js";
```

Here's my environment:
* Ubuntu 22.04
* svelte-notifications: ^0.9.93
* svelte-kit: 1.0.0-next.324

Some potentially useful links:
* https://popper.js.org/docs/v2/#distribution-targets
* https://svelte.dev/repl/318f2c2ca4174a97befe0840936b9eec?version=3.23.0 

-------------------
Edit: Found a workaround!

Based on a [related issue](https://github.com/bestguy/sveltestrap/pull/356), I manually edited the file ```node_modules/@popperjs/core/package.json``` and defined the type as "module":

```json
{
  "name": "@popperjs/core",
  "type": "module",
```

It's a hack, but at least it lets svelte-kit import the package so we can continue to use svelte-notifications in development.

**Comment by rationalquality** [comment]
Most likely I'll return the old build system with esm and etc.. I'll solve this issue later

**Comment by rationalquality** [comment]
I'll try to finish this today. Sorry for such development delays

**Comment by rationalquality** [comment]
Hey guys. I have released a new version. Please try to see if it fixes the issue. Right now I am actively developing a new version of the package. I will try to foresee all possible problems with the build

**Comment by jonjes** [comment]
Hi Sergey, thanks for working on this. I appreciate it (especially when so much craziness is happening over there lately...). Unfortunately with the latest version, I'm still getting the same issue, but at least the workaround above still works, and it's easy to do. 
Hmm, I think the issue might be between the popperjs library and the vite system that svelte-kit uses, but I'm not really sure about the details.

**Comment by rationalquality** [comment]
@jonjes I released new patch version with fix. Please, test it and let me know how it works

**Comment by rationalquality** [comment]
Hi @winston0410, could you check how it works with the new changes?

**Comment by jonjes** [comment]
Hmm, thanks for updating it, but unfortunately I don't see a difference in my testing.  With svelte-kit, it builds for production just fine, but when I run it in development mode, I still get this error:

```
[project_directory]/node_modules/@popperjs/core/dist/esm/popper.js:1
import { popperGenerator, detectOverflow } from "./createPopper.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
```

Just thinking: It could be because my project was started with a much earlier version of svelte-kit. I'll create a new test project with the latest version of svelte-kit to see whether I still see this issue.

**Comment by rationalquality** [comment]
@jonjes is really this package issue? Can you try using svelte-notifications with clean svelte-kit setup?
